name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test-image:
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull DOCKER_USERNAME/cicd-a3

      - name: Run tests
        run: |
          docker run --rm cicd-a3 python test.py

